// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	/**  `{ game: "cstrike", ... }` or plain invocation for defaults. */
	startScan: (config: {
	/**  `"cstrike" | "czero" | "valve" | …` (see `Game::parse`). */
	game?: string | null,
	fetchRounds?: number | null,
	fetchAll?: boolean | null,
	concurrency?: number | null,
	queryTimeoutMs?: number | null,
	/**  Force a fresh list from Steam rather than the local cache. */
	rediscover?: boolean | null,
	/**  Discovery filters — the four the in-game dialog sends on the wire. */
	filters?: Filters | null,
	maxServers?: number | null,
	verbose?: boolean | null,
} | null) => typedError<null, string>(__TAURI_INVOKE("start_scan", { config })),
	/**
	 *  Ask the in-flight sweep to stop. Nothing is aborted mid-query; results that
	 *  already arrived are kept.
	 */
	stopScan: () => __TAURI_INVOKE<void>("stop_scan"),
	/**
	 *  Re-query one endpoint. `Err` carries the pacing refusal reason, so the UI
	 *  can say "paced" rather than showing the server as dead.
	 * 
	 *  `interactive` marks a refresh the user asked for on this one server (see
	 *  `QueryGate::try_acquire_interactive`); a bulk refresh of many rows passes
	 *  `false` and keeps the sweep's limits.
	 */
	refreshServer: (endpoint: string, interactive: boolean) => typedError<null, string>(__TAURI_INVOKE("refresh_server", { endpoint, interactive })),
	/**
	 *  One server's player list, for Game Info: the sweep never asks for it,
	 *  and everything else in the row is already measured. `Err` carries the
	 *  pacing refusal or the query failure.
	 */
	serverPlayers: (endpoint: string) => typedError<PlayerRow[], string>(__TAURI_INVOKE("server_players", { endpoint })),
	/**  Drop bans, the recheck queue and pacing, then rescan. */
	hardRefresh: (config: {
	/**  `"cstrike" | "czero" | "valve" | …` (see `Game::parse`). */
	game?: string | null,
	fetchRounds?: number | null,
	fetchAll?: boolean | null,
	concurrency?: number | null,
	queryTimeoutMs?: number | null,
	/**  Force a fresh list from Steam rather than the local cache. */
	rediscover?: boolean | null,
	/**  Discovery filters — the four the in-game dialog sends on the wire. */
	filters?: Filters | null,
	maxServers?: number | null,
	verbose?: boolean | null,
} | null) => typedError<string, string>(__TAURI_INVOKE("hard_refresh", { config })),
	/**  The ban list. */
	bans: () => __TAURI_INVOKE<BanRow[]>("bans"),
	/**
	 *  The Banned tab's `Clear bans`: drop every ban without touching pacing.
	 * 
	 *  `u32` because this crosses into the webview, where Specta refuses
	 *  pointer-width integers (JSON numbers are f64).
	 */
	clearBans: () => __TAURI_INVOKE<number>("clear_bans"),
	banServer: (endpoint: string, hostname: string) => typedError<null, string>(__TAURI_INVOKE("ban_server", { endpoint, hostname })),
	whitelistServer: (endpoint: string) => typedError<null, string>(__TAURI_INVOKE("whitelist_server", { endpoint })),
	/**
	 *  Rows from the local discovery cache, so the list paints before any network
	 *  work. Empty when the cache is missing or was built for another filter.
	 */
	cachedRows: () => __TAURI_INVOKE<ServerRow[]>("cached_rows"),
	/**
	 *  Join a server through Steam: `steam://connect/<ip>:<port>/`.
	 * 
	 *  Steam starts (or reuses) the game and connects it, exactly as joining
	 *  from the in-game browser does, so no install path has to be configured.
	 *  The endpoint is re-parsed rather than pasted into the URL, so nothing but
	 *  a plain `ip:port` can reach the URL handler. Returns the URL it opened.
	 */
	connect: (endpoint: string) => typedError<string, string>(__TAURI_INVOKE("connect", { endpoint })),
	/**  The Settings dialog's current state. */
	getSettings: () => __TAURI_INVOKE<SettingsView>("get_settings"),
	/**
	 *  Save (or, with an empty string, clear) the Steam Web API key.
	 * 
	 *  Takes effect for the next sweep: `start_scan` carries `api_key` over from
	 *  the live config, which this updates in place.
	 */
	setApiKey: (key: string) => typedError<SettingsView, string>(__TAURI_INVOKE("set_api_key", { key })),
	/**
	 *  Enable or disable `debug`-level entries in the log file. Takes effect
	 *  immediately (see `logging::LoggingHandle::set_debug`) and is persisted so
	 *  the next run starts with the same level.
	 */
	setDebugLogs: (enabled: boolean) => typedError<SettingsView, string>(__TAURI_INVOKE("set_debug_logs", { enabled })),
	/**
	 *  Open Steam's API-key page in the default browser.
	 * 
	 *  Takes no argument on purpose: the page can open exactly this one URL,
	 *  never an arbitrary one, so no URL permission is granted to the webview.
	 */
	openApiKeyPage: () => typedError<null, string>(__TAURI_INVOKE("open_api_key_page")),
	/**
	 *  Open the GitHub repository in the default browser.
	 * 
	 *  Same reasoning as [`open_api_key_page`]: one fixed URL, no arbitrary-URL
	 *  permission granted to the webview. A plain `<a target="_blank">` cannot do
	 *  this itself — the webview has no such permission either.
	 */
	openRepositoryPage: () => typedError<null, string>(__TAURI_INVOKE("open_repository_page")),
};

/** Events */
export const events = {
	scan: makeEvent<Event>("scan"),
};

/* Types */
/**  A ban-list row for the `B` overlay. */
export type BanRow = {
	endpoint: string,
	/**  The hostname as last seen before the ban; empty if never measured. */
	hostname: string,
	/**  `%Y-%m-%d %H:%M`. */
	banned_at: string,
	reasons: string[],
	rechecks: number,
};

/**
 *  Everything the UI is told during a scan.
 * 
 *  One enum behind one event name: the frontend needs exactly one listener.
 */
export type Event = { kind: "phase"; phase: Phase } | 
/**
 *  Bulk rows — from the cache, or one fetch round. Sent before scanning so
 *  the list is browsable immediately.
 */
{ kind: "listed"; rows: ServerRow[] } | 
/**  One scan result. `done`/`total` count the sweep, not the list. */
{ kind: "row"; done: number; total: number; row: ServerRow } | 
/**  A suspect was re-queried and replaces its earlier row. */
{ kind: "refreshed"; row: ServerRow } | 
/**  A refresh was refused by the per-endpoint pacing gate. */
{ kind: "paced"; endpoint: string; reason: string } | { kind: "summary"; summary: ScanSummary } | { kind: "error"; message: string };

/**
 *  Discovery filters — the values that change *what Steam is asked for*.
 * 
 *  These are the four the in-game filter dialog sends on the wire (see
 *  `protocol::masterserver::build_filter`). Changing any of them invalidates
 *  the cached server list, because the cache is keyed on the filter string.
 * 
 *  `rename_all = "camelCase"` matters: `ScanConfig` is camelCase on the wire,
 *  and without this the nested filter object would demand `no_full` from a
 *  frontend that sends `noFull` — a mismatch that surfaces at runtime as
 *  `missing field`, not as a compile error.
 */
export type Filters = {
	secure: boolean,
	noFull: boolean,
	noEmpty: boolean,
	noPassword: boolean,
};

/**  Progress phase. */
export type Phase = "idle" | "fetching" | "scanning" | "done";

/**  One player, as shown in the detail pane. */
export type PlayerRow = {
	index: number,
	name: string,
	score: number,
	duration_seconds: number | null,
};

/**  Frontend's scan request. Field names are `camelCase` on the JS side. */
export type ScanConfig = {
	/**  `"cstrike" | "czero" | "valve" | …` (see `Game::parse`). */
	game?: string | null,
	fetchRounds?: number | null,
	fetchAll?: boolean | null,
	concurrency?: number | null,
	queryTimeoutMs?: number | null,
	/**  Force a fresh list from Steam rather than the local cache. */
	rediscover?: boolean | null,
	/**  Discovery filters — the four the in-game dialog sends on the wire. */
	filters?: Filters | null,
	maxServers?: number | null,
	verbose?: boolean | null,
};

/**
 *  Counters for the status line.
 * 
 *  `u32`, not `usize`: this type crosses into the webview, where a JSON number
 *  is an f64 and Specta refuses the pointer-width integers outright. A server
 *  count cannot approach 2^32.
 */
export type ScanSummary = {
	shown: number,
	banned: number,
	hidden: number,
	paced: number,
	listed: number,
	measured: number,
	rechecks: number,
	total_before: number,
};

/**
 *  A flat, serialisable projection of [`ScannedServer`].
 * 
 *  `ScannedServer` / `Analysis` / `Outcome` deliberately do not derive
 *  `Serialize` — they are detection internals. This is the single projection
 *  they cross the wire through.
 */
export type ServerRow = {
	/**  `"1.2.3.4:27015"`. */
	endpoint: string,
	hostname: string,
	map: string,
	gamedir: string,
	/**
	 *  The server's own game description (the in-game Game column):
	 *  `"Counter-Strike"` unless a mod reports something else.
	 */
	game: string,
	players: number,
	max_players: number,
	bots: number,
	/**
	 *  The bot plugin the server's rules name (`"YaPB 4.4.957"`), which can
	 *  hide its bots from `bots`. `None` when none was found or not asked.
	 */
	bot_plugin: string | null,
	/**  `None` when the server was listed by Steam but never answered A2S. */
	ping_ms: number | null,
	secure: boolean,
	password: boolean,
	/**  `0` windows, `1` linux, `2` mac — the in-game browser's icon column. */
	os: number,
	/**  Answered A2S on this run, so every field is measured rather than listed. */
	live: boolean,
	/**
	 *  `"ok" | "listed" | "timeout" | "paced" | "banned" | "bad-header" |
	 *  "refused" | "err"`.
	 */
	outcome: string,
	banned: boolean,
	/**  Any hard reason — the row is a definite fake. */
	fake: boolean,
	/**
	 *  Fully verified: the server answered A2S itself (this sweep, or earlier
	 *  this session when it was paced and nothing was sent) **and** passed
	 *  every check, including the listing-wide ones (redirect farms, cloned
	 *  names) and name history. The default view shows only these rows.
	 */
	verified: boolean,
	reasons: string[],
	soft_reasons: string[],
	country: string | null,
	version: string,
	players_list: PlayerRow[],
};

/**
 *  What the Settings dialog shows. The key itself never crosses back into
 *  the webview — only a masked hint, so it cannot leak through the UI.
 */
export type SettingsView = {
	/**  `••••••••1A2B`, or `None` when no key is configured anywhere. */
	api_key_hint: string | null,
	/**  `"settings"` (a key is saved) or `"none"`. */
	api_key_source: string,
	/**  Where a key is minted. */
	api_key_url: string,
	/**  Whether `debug`-level entries are written to the log file. */
	debug_logs: boolean,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<T>(name: string, serialize?: (payload: T) => unknown, deserialize?: (payload: any) => T) {
    const mapEvent = (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload: T) => serialize ? serialize(payload) : payload;

    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, mapEvent(cb)),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, mapEvent(cb)),
        emit: ((payload: T) => target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    });

    return Object.assign(fn, base);
}

