// Builds the static website from docs/src/ into docs/index.html,
// docs/style.css and docs/site.js. GitHub Pages serves docs/ as is, so the generated files are
// committed; `--check` fails when they are out of date instead of writing.
//
//   <!-- @include sections/hero.html -->   inlines docs/src/sections/hero.html
//   @import "./styles/hero.css";           inlines docs/src/styles/hero.css
//   {{repo}}                               replaced with SITE.repo

import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { dirname, join, relative } from "node:path";
import { fileURLToPath } from "node:url";

const SITE = {
  repo: "vuxsoftware/cs16browser",
};

const docs = join(dirname(fileURLToPath(import.meta.url)), "..", "docs");
const src = join(docs, "src");

function read(path) {
  return readFileSync(path, "utf8").replace(/\r\n/g, "\n");
}

function expand(path, pattern) {
  return read(path).replace(pattern, (_, file) => {
    const target = join(dirname(path), file);
    if (!existsSync(target)) throw new Error(`${relative(docs, path)}: missing ${file}`);
    return expand(target, pattern).trimEnd();
  });
}

function fill(text) {
  return text.replace(/\{\{(\w+)\}\}/g, (match, key) => {
    if (!(key in SITE)) throw new Error(`unknown placeholder ${match}`);
    return SITE[key];
  });
}

const banner = "Generated by scripts/build-site.mjs from docs/src/. Edit those files, then run `bun run site`.";
const html = fill(expand(join(src, "index.html"), /^[ \t]*<!-- @include (\S+) -->$/gm)).replace(
  "<!doctype html>\n",
  `<!doctype html>\n<!-- ${banner} -->\n`,
);
const css = `/* ${banner} */\n\n` + expand(join(src, "style.css"), /^@import "(\S+)";$/gm);

const outputs = { "index.html": html, "style.css": css, "site.js": read(join(src, "site.js")) };
const check = process.argv.includes("--check");
const stale = [];

for (const [name, content] of Object.entries(outputs)) {
  const path = join(docs, name);
  if (check) {
    if (!existsSync(path) || read(path) !== content) stale.push(name);
  } else {
    writeFileSync(path, content);
  }
}

if (stale.length) {
  console.error(`docs/${stale.join(", docs/")} out of date; run \`bun run site\`.`);
  process.exit(1);
}
console.log(check ? "Website is up to date." : "Built docs/index.html, docs/style.css and docs/site.js.");
